### ISSUE TITLE
Crash in Debug for Client:Host mode of operation

### ISSUE THREAD

**Issue by SteveBz** [byggemandboesen/H-line-software#2]
Hi Victor,

I've been using the -d option when operating in Client:Host mode. Client is on a Linux PC, Host is on a RPi3b+ with a 2020 Version of OS RPi.  Here is the error:
```

python3 H-line.py -s 2400000 -r 11 -n 1000 -l 51 -g 0 -z 0 -a 51 -e 192.168.1.116 -m 3 -i 0 -d
Receiving 1000 bins of 2048 samples each...
Traceback (most recent call last):
  File "H-line.py", line 178, in <module>
    parser()
  File "H-line.py", line 45, in parser
    main(args)
  File "H-line.py", line 98, in main
    write_debug(freqs, data, args, ra, dec)
  File "H-line.py", line 155, in write_debug
    "Data": data.tolist()
AttributeError: 'list' object has no attribute 'tolist'

```
I haven't tested it in single machine operation, but in client/host the following fixes it, you obviously know better than me if it will fail in both modes, in which case I've over-engineered the answer.  Maybe you can just remove the second `.to list()` from `data.tolist()`

Here it is:

  ```
    if not isinstance(data, list):
        data = data.tolist()
    data = {
        "Freqs": freqs.tolist(),
        "Data": data
    }
```

Good luck.

Kind regards

Steve.

**Comment by byggemandboesen** [comment]
Thanks for pointing it out 😉 It should work when not streaming from RTL-TCP, but I'll fix the issue with your current solution until I can have a proper look at it.
Thanks!
